In [1]:
# PYTHON LISTS -> HETEROGENEOUS!

In [2]:
a = [1, 4.5, "string", True, 1234567890, "this is a very lengthy string!"]

In [3]:
a

[1, 4.5, 'string', True, 1234567890, 'this is a very lengthy string!']

In [4]:
'''
Numpy Arrays -> Homogeneous Data
Python Lists -> Heterogeneous Data
'''

'\nNumpy Arrays -> Homogeneous Data\nPython Lists -> Heterogeneous Data\n'

In [5]:
import math as m

In [6]:
m.log(10)

2.302585092994046

In [7]:
import numpy as np

In [8]:
a = [1, 2, 3, 4, 5]

In [11]:
a_cubes = [ i ** 3 for i in a ]

In [12]:
a_cubes

[1, 8, 27, 64, 125]

In [13]:
b = np.array(a) # Typecasting a python list into a numpy array

In [14]:
b

array([1, 2, 3, 4, 5])

In [16]:
type(b) # N - Dimensional Array

numpy.ndarray

In [17]:
# Numpy Arrays support element wise operation -> Broadcasting

In [18]:
a ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [19]:
b ** 3

array([  1,   8,  27,  64, 125])

In [20]:
%timeit [i ** 2 for i in a]

1.35 µs ± 17.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [21]:
%timeit [ i ** 3 for i in range(100000) ]

30.4 ms ± 2.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [22]:
l = np.array(range(100000))

In [23]:
%timeit l ** 3

133 µs ± 383 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [24]:
'''
Why is numpy so much faster than python lists?
    - Homogeneous
    - Divide tasks in parallel processes
    - Numpy functions are directly implemented in C
'''

'\nWhy is numpy so much faster than python lists?\n    - Homogeneous\n    - Divide tasks in parallel processes\n    - Numpy functions are directly implemented in C\n'

In [25]:
a = np.array(range(10000))

In [26]:
a

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [27]:
a.ndim # Number of dimensions within the data

1

In [29]:
a.shape # Number of elements in each dimension represented as a tuple

(10000,)

In [30]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [31]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
b.ndim

2

In [33]:
b.shape

(4, 3)

In [34]:
a = np.array([1,2,3,4,5,6,7,8])

In [35]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
print(a.ndim, a.shape)

1 (8,)


In [37]:
# np.arange(start, end, step_size) -> arange has a single "r"

In [38]:
a1 = np.arange(1, 5) # defeault step size is 1

In [40]:
a1 # start is included and end is not included

array([1, 2, 3, 4])

In [41]:
a2 = np.arange(1, 10, 2)

In [42]:
a2

array([1, 3, 5, 7, 9])

In [43]:
a3 = np.array(range(1, 10, 2))

In [44]:
a3

array([1, 3, 5, 7, 9])

In [45]:
# np.arange has a special superpower -> IT CAN WORK WITH FLOATING VALUES

In [46]:
a4 = np.arange(1, 5, 0.5)

In [47]:
a4

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [48]:
1.

1.0

In [49]:
a4

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [50]:
# Positive Indexes, Negative Indexes and Slices all work with np arrays

In [51]:
a4[5]

3.5

In [52]:
a4[-3]

3.5

In [53]:
a4[2:7]

array([2. , 2.5, 3. , 3.5, 4. ])

In [54]:
l = [1,2,3,4,5,6,7,8,9,10]

In [55]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [57]:
l[1,6,4,7] # Fetching elements at random indexes which are not in a sequence

TypeError: list indices must be integers or slices, not tuple

In [58]:
a4

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [86]:
a4[[1,6,4,70]]

IndexError: index 70 is out of bounds for axis 0 with size 8

In [60]:
b1 = np.array([1, 2, 3, 4, 5, 6.0])

In [62]:
b1 # Automatically raised all integers to float -> TO MAINTAIN HOMOGENEITY

array([1., 2., 3., 4., 5., 6.])

In [63]:
b2 = np.array(["bipin kalra", 1, 2, 3, 4.5])

In [64]:
b2

array(['bipin kalra', '1', '2', '3', '4.5'], dtype='<U32')

In [69]:
b3 = np.array([1, 2, 3, 4], dtype = "<U32")

In [70]:
b3

array(['1', '2', '3', '4'], dtype='<U32')

In [71]:
'''
TYPECASTING IN 2 WAYS ->
AUTOMATIC -> Intrinsic
MANUAL (User Based) -> Extrinsic
'''

'\nTYPECASTING IN 2 WAYS ->\nAUTOMATIC -> Intrinsic\nMANUAL (User Based) -> Extrinsic\n'

In [72]:
b4 = np.array(["this", "is", "absurd!"], dtype = "float")

ValueError: could not convert string to float: 'this'

In [73]:
# FANCY INDEXING

In [74]:
a = np.array(range(1, 11))

In [75]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
a < 6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [77]:
a[[3,6,5,2]]

array([4, 7, 6, 3])

In [79]:
print(a[a < 6])

'''
[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]
[ True, True, True, True, True, False, False, False, False, False]

Only keeps values wherever the corresponding result is True.
'''

[1 2 3 4 5]


'\n[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]\n[ True, True, True, True, True, False, False, False, False, False]\n\nOnly keeps values wherever the corresponding result is True.\n'

In [84]:
a[a % 2 == 0] # ACTS LIKE A FILTER

array([ 2,  4,  6,  8, 10])

# NPS CASE

In [ ]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK