# 2D Arrays

In [1]:
import numpy as np

In [2]:
a = np.arange(16)

In [3]:
a.ndim

1

In [4]:
a.shape

(16,)

In [6]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
# np_array.reshape(num_rows, num_cols)

In [7]:
a.reshape(8, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [8]:
a.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
a.reshape(4, 5)
# num_rows * num_cols = num_elements

ValueError: cannot reshape array of size 16 into shape (4,5)

In [12]:
# YOU ARE GOING TO GET A RANDOM DATASET
# YOU HAVE TO ARRANGE IT IN 8 COLUMNS

In [13]:
a.reshape(8, -1)
# -1 denotes that you want Python to calculate the other dimension

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [14]:
a.reshape(-1, 8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [15]:
a.reshape(-1, -1) # AMBIGUITY

ValueError: can only specify one unknown dimension

# INDEXING

In [53]:
a = a.reshape(8, 2)

ValueError: cannot reshape array of size 12 into shape (8,2)

In [17]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [18]:
len(a) # number of rows

8

In [20]:
len(a[0]) # number of columns

2

In [21]:
a = np.arange(12)

In [22]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
a = a.reshape(3, 4)

In [24]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
# FUNCTION CHAINING

In [26]:
b = np.arange(12).reshape(3, 4)

In [27]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
b.shape

(3, 4)

In [29]:
b.T # Every array in numpy already has it's transpose attached to it as T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [30]:
b.T.shape

(4, 3)

In [31]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
b[0][1] # np_array[row_number][col_number]

1

In [35]:
b[0, 1] # Only works in Numpy Arrays, Not in Python Lists

1

In [36]:
c = np.arange(9).reshape(3, 3)

In [37]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
d = np.arange(10)

In [39]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
d[[4,2,3,6]]

array([4, 2, 3, 6])

In [41]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
c[[0,2,0],[1,1,0]] # c[0, 1], c[2, 1], c[0, 0]

# [0,2,0]
# [1,1,0]

array([1, 7, 0])

In [43]:
c[[0,2,0],[1,1,5]]

IndexError: index 5 is out of bounds for axis 1 with size 3

In [44]:
c[[0,2,0],[1,1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [46]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
c[[0,1,2], [0,1,2]]

array([0, 4, 8])

In [48]:
test = np.arange(64).reshape(8, 8)

In [49]:
test

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [50]:
len(test)

8

In [51]:
list(range(len(test)))

[0, 1, 2, 3, 4, 5, 6, 7]

In [52]:
test[list(range(len(test))), list(range(len(test)))]

array([ 0,  9, 18, 27, 36, 45, 54, 63])

In [54]:
# SLICING

In [55]:
a = np.arange(12).reshape(3, 4)

In [56]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a[:2] # Slicing works on rows by default

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
a[:, 1:3] # Second slice works on columns

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [59]:
a[:2, 1:3]

array([[1, 2],
       [5, 6]])

In [60]:
test

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [61]:
test[3:7:2, 1:6:3]

array([[25, 28],
       [41, 44]])

In [62]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])

In [63]:
a[3:]

array([4, 5])

In [79]:
b[::-2]

array([6, 8])

In [80]:
a[3:] = b[::-2]

In [81]:
a

array([1, 2, 3, 6, 8])

In [72]:
c = np.array([1,2,3,4,5,6,7,8])

In [73]:
c[4:]

array([5, 6, 7, 8])

In [74]:
c[4:] = [100]

In [75]:
c

array([  1,   2,   3,   4, 100, 100, 100, 100])

In [76]:
c = np.array([1,2,3,4,5,6,7,8])

In [77]:
c[4:] = [100, 200, 300, 400]

In [78]:
c

array([  1,   2,   3,   4, 100, 200, 300, 400])

In [82]:
a = np.arange(12).reshape(3, 4)

In [83]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
a < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [86]:
a[a < 6] # The result will be 1D

array([0, 1, 2, 3, 4, 5])

# Aggregate Functions

In [87]:
a = np.arange(1, 11)

In [88]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
np.sum(a)

55

In [90]:
np.mean(a)

5.5

In [91]:
np.min(a)

1

In [92]:
np.max(a)

10

In [93]:
b = np.arange(12).reshape(3, 4)

In [94]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
np.sum(b)

66

In [97]:
np.sum(b, axis = 0) # SUM FOR EACH COLUMN

array([12, 15, 18, 21])

In [98]:
np.sum(b, axis = 1) # SUM FOR EACH ROW

array([ 6, 22, 38])

# Logical Operations

In [105]:
prices = np.array([50, 45, 30, 40, 35])

In [106]:
can_afford = np.any(prices <= 30)
# Returns True if even a single value satisfies the condition

In [107]:
can_afford

True

In [102]:
task_completion = np.array([1,1,1,1,1,1,1,0])

In [103]:
can_go_out_and_play = np.all(task_completion == 1)
# Returns True only if every single value satisfies the condition

In [104]:
can_go_out_and_play

False

In [108]:
a = np.array([[-3,4,27,34,-2, 0, -45,-11,4, 0]])

In [109]:
a[a > 0] = 1
a[a < 0] = -1

In [110]:
a

array([[-1,  1,  1,  1, -1,  0, -1, -1,  1,  0]])

In [111]:
# np.where(condition, value_if_true, value_if_false)

In [112]:
prices = np.array([45, 55, 60, 30, 75, 20, 100, 90])

In [114]:
prices[prices >= 50] = prices[prices >= 50] * 0.9

# TOO COMPLEX

In [115]:
prices

array([45, 49, 54, 30, 67, 20, 90, 81])

In [116]:
prices = np.array([45, 55, 60, 30, 75, 20, 100, 90])

In [117]:
discounted_prices = np.where(prices >= 50, prices * 0.9, prices)

In [118]:
discounted_prices

array([45. , 49.5, 54. , 30. , 67.5, 20. , 90. , 81. ])