In [12]:
import numpy as np

In [13]:
a = np.arange(12).reshape(-1, 4)

In [14]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
b = np.arange(12).reshape(-1, -1)

ValueError: can only specify one unknown dimension

In [26]:
a = np.array([7, 0, 4, 8, 2, 1, 3, 5, 6, 9])

In [27]:
a_sorted = np.sort(a)

In [28]:
a_sorted

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a # np.sort(array) is not inplace and thus does not change the original array

array([7, 0, 4, 8, 2, 1, 3, 5, 6, 9])

In [30]:
a.sort()

In [31]:
a # sorting using array.sort() is performed inplace

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Element Wise Operations

In [32]:
a = np.arange(1, 6)

In [33]:
a

array([1, 2, 3, 4, 5])

In [34]:
a * 5 

array([ 5, 10, 15, 20, 25])

In [35]:
a

array([1, 2, 3, 4, 5])

In [36]:
b = np.arange(6, 11)

In [37]:
b

array([ 6,  7,  8,  9, 10])

In [40]:
a * b

# [1, 2, 3, 4, 5]
# [6, 7, 8, 9, 10]
# BOTH ARRAYS SHOULD HAVE THE SAME SHAPE!

array([ 6, 14, 24, 36, 50])

In [41]:
c = np.array([1, 2, 3])

In [43]:
a * c
# a and c do not have the same shape

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [44]:
d = np.arange(12).reshape(3, 4)
e = np.arange(13, 25).reshape(3, 4)

In [45]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
e

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [47]:
d * e

array([[  0,  14,  30,  48],
       [ 68,  90, 114, 140],
       [168, 198, 230, 264]])

In [48]:
d * 5

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [49]:
'''
Array * number -> WORKS
Array * Array (same shape) -> WORKS
Array * Array (different shape) -> DOES NOT WORK!
'''

'\nArray * number -> WORKS\nArray * Array (same shape) -> WORKS\nArray * Array (different shape) -> DOES NOT WORK!\n'

# Matrix Multiplication

In [50]:
# Number of columns in Array1 should be equal to number of rows in Array2

In [51]:
# (A,B) * (B,C) -> (A,C)
# (3,4) * (4,3) -> (3,3)

In [52]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(2,14).reshape(4,3)

In [53]:
a.shape

(3, 4)

In [54]:
b.shape

(4, 3)

In [55]:
np.dot(a, b)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [56]:
np.matmul(a, b)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [57]:
a@b

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [58]:
a@5

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [59]:
np.matmul(a, 5)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [62]:
np.dot(a, 5)

# np.dot supports both matrix multiplication and
# element wise multiplication

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

# VECTORIZE

In [63]:
'''
Array -> Function -> Modified Array -----> Loops
'''

'\nArray -> Function -> Modified Array -----> Loops\n'

In [64]:
a = np.arange(10)

In [65]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
def random_operation(x):
    if x % 2 == 0:
        x += 2
    else:
        x -= 2
        
    return x

In [68]:
random_operation(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [69]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [70]:
cool_operation = np.vectorize(random_operation)

In [71]:
type(cool_operation)

numpy.vectorize

In [72]:
cool_operation(a)

array([ 2, -1,  4,  1,  6,  3,  8,  5, 10,  7])

In [78]:
import math

In [79]:
math.log(5)

1.6094379124341003

In [80]:
math.log(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [81]:
# new_log = np.vectorize(math.log)

In [83]:
# new_log(a)

In [84]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Broadcasting

In [89]:
a = np.tile([0,10,20,30], (3,1))

# np.tile(array, (repetition_rows, repetition_cols))

In [90]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [91]:
a = a.T

In [92]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [93]:
b = np.tile([0,1,2], (4,1))

In [94]:
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [97]:
a + b

# Since a and b have the same shape
# They can be added without any issues.

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [98]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [99]:
c = np.array([0,1,2])

In [100]:
c

array([0, 1, 2])

In [102]:
a + c

# c was broadcasted along rows (vertically)
# so that a and c can be made compatible

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [111]:
d = np.array([0,10,20,30]).reshape(4,1)

In [112]:
d

array([[ 0],
       [10],
       [20],
       [30]])

In [113]:
d.shape

(4, 1)

In [115]:
d + c

# d was stacked (broadcasted) along columns (horizontally)
# c was stacked (broadcasted) along rows (vertically)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [116]:
x = np.arange(8).reshape(2,4)
y = np.arange(16).reshape(4,4)

In [117]:
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [118]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [119]:
x + y

ValueError: operands could not be broadcast together with shapes (2,4) (4,4) 

In [120]:
'''
2D Arrays ->
A + A (Same shape)-> Works
A + A (1D) -> Works
A + number -> Works

A + A (different shape but still 2D) -> DOES NOT WORK!
'''

'\n2D Arrays ->\nA + A (Same shape)-> Works\nA + A (1D) -> Works\nA + number -> Works\n\nA + A (different shape but still 2D) -> DOES NOT WORK!\n'