In [17]:
import numpy as np

In [18]:
a = np.arange(4)

In [19]:
a

array([0, 1, 2, 3])

In [20]:
b = a.reshape(2, 2)

In [21]:
b

array([[0, 1],
       [2, 3]])

In [22]:
a[0] = 100

In [23]:
a

array([100,   1,   2,   3])

In [24]:
b

array([[100,   1],
       [  2,   3]])

In [25]:
# np.shares_memory(array_1, array_2)

In [26]:
np.shares_memory(a, b) # Shallow copy

True

In [27]:
a = np.arange(4)

In [28]:
c = a + 2

In [29]:
a

array([0, 1, 2, 3])

In [30]:
c

array([2, 3, 4, 5])

In [32]:
np.shares_memory(a, c) # Deep Copy

False

In [33]:
c[0] = 100

In [34]:
c

array([100,   3,   4,   5])

In [35]:
a

array([0, 1, 2, 3])

In [36]:
a = np.zeros(4)

In [37]:
a

array([0., 0., 0., 0.])

In [38]:
d = a * 2

In [39]:
a

array([0., 0., 0., 0.])

In [40]:
d

array([0., 0., 0., 0.])

In [41]:
np.shares_memory(a, d)

False

In [42]:
a = np.arange(10)

In [43]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
b = a [::2]

In [45]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
b

array([0, 2, 4, 6, 8])

In [47]:
np.shares_memory(a, b)

True

In [48]:
a[0] = 1000

In [49]:
b

array([1000,    2,    4,    6,    8])

In [50]:
a = np.arange(6)

In [51]:
a

array([0, 1, 2, 3, 4, 5])

In [52]:
b = a[a % 1 == 0]

In [53]:
b

array([0, 1, 2, 3, 4, 5])

In [54]:
b[0] = 10

In [55]:
a[0]

0

In [56]:
np.shares_memory(a, b)

False

In [57]:
'''
Memory in Numpy ->
    - Shallow Copy - Reshaping, Slicing...
    - Deep Copy - Arithmetic Operations, Masking...
'''

'\nMemory in Numpy ->\n    - Shallow Copy - Reshaping, Slicing...\n    - Deep Copy - Arithmetic Operations, Masking...\n'

In [58]:
a = np.arange(10)

In [59]:
a_shallow_copy = a.view()
# Creates a shallow copy of a

In [60]:
np.shares_memory(a_shallow_copy, a)

True

In [61]:
a_deep_copy = a.copy()
# Creates a deep copy of a

In [62]:
np.shares_memory(a_deep_copy, a)

False

#### `.copy()`
Returns copy of the array.

Documentation (`.copy()`): https://numpy.org/doc/stable/reference/generated/numpy.ndarray.copy.html#numpy.ndarray.copy

Documentation: (`np.copy()`): https://numpy.org/doc/stable/reference/generated/numpy.copy.html

# SPLITTING DATA

In [63]:
a = np.arange(9)

In [64]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
# Splitting in n equal sections

In [66]:
np.split(a, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [67]:
# IMPORTANT REQUISITE -> 
# Number of elements in the array should be divisible by number of sections

In [68]:
b = np.arange(10)

In [69]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.split(b, 3)

ValueError: array split does not result in an equal division

In [71]:
b[0:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
result = np.split(b[0:-1], 3)

In [73]:
result

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [74]:
# Splitting on the basis of exact indices

In [75]:
c = np.arange(16)

In [76]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [77]:
np.split(c, [3, 5, 9])

[array([0, 1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15])]

In [78]:
a = np.arange(48).reshape(8,6)

In [79]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])

In [80]:
np.hsplit(a, 2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32],
        [36, 37, 38],
        [42, 43, 44]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35],
        [39, 40, 41],
        [45, 46, 47]])]

In [81]:
np.hsplit(a, [2, 5])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31],
        [36, 37],
        [42, 43]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16],
        [20, 21, 22],
        [26, 27, 28],
        [32, 33, 34],
        [38, 39, 40],
        [44, 45, 46]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35],
        [41],
        [47]])]

In [82]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])

In [83]:
np.vsplit(a, 4)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]),
 array([[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]])]

In [84]:
np.vsplit(a, [1, 6])

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]),
 array([[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]])]

# STACKING

In [85]:
a = np.arange(1, 5)
b = np.arange(2, 6)
c = np.arange(3, 7)

In [86]:
a

array([1, 2, 3, 4])

In [87]:
b

array([2, 3, 4, 5])

In [88]:
c

array([3, 4, 5, 6])

In [89]:
np.vstack([b, c, a])

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [1, 2, 3, 4]])

In [90]:
a = np.arange(1, 5)
b = np.arange(2, 4)
c = np.arange(3, 10)

In [91]:
np.vstack([b, c, a])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 7

In [92]:
a = np.arange(10).reshape(2, 5)

In [93]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [94]:
b = np.arange(50).reshape(10, 5)

In [95]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [96]:
np.vstack([a, b])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [97]:
np.vstack(a, b)

TypeError: vstack() takes 1 positional argument but 2 were given

In [98]:
a = np.arange(5).reshape(5, 1)

In [99]:
a

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [100]:
b = np.arange(15).reshape(5, 3)

In [101]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [102]:
np.hstack([a, b])

array([[ 0,  0,  1,  2],
       [ 1,  3,  4,  5],
       [ 2,  6,  7,  8],
       [ 3,  9, 10, 11],
       [ 4, 12, 13, 14]])

In [103]:
# CONCATENATE -> can perform both vstack and hstack

In [104]:
a = np.array([1,2,3])
b = np.array([[1,2,3], [4,5,6]])

In [105]:
a

array([1, 2, 3])

In [106]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
np.concatenate([a, b], axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [108]:
# concatenate can only work if both a and b have the same number of dimensions

In [109]:
a = np.array([[1,2,3]])
b = np.array([[1,2,3], [4,5,6]])

In [111]:
np.concatenate([a, b], axis = 0) # axis = 0 -> vstack

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [113]:
a = np.arange(6).reshape(3, 2)
b = np.arange(9).reshape(3, 3)

In [114]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [115]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
np.concatenate([a, b], axis = 1) # axis = 1 -> hstack

array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [117]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6,7,8]])

In [118]:
a

array([[1, 2],
       [3, 4]])

In [119]:
b

array([[5, 6, 7, 8]])

In [121]:
np.concatenate([a, b], axis = None)

# axis = None joins and converts to 1D

array([1, 2, 3, 4, 5, 6, 7, 8])

In [122]:
a = np.arange(9).reshape(3, 3)

In [123]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [124]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])